version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: notli-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notli
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - notli-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notli"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  notli-pg-data:
    driver: local
